baseURL = "https://jbourgin.github.io"
languageCode = "en-us"
title = "Jessica Bourgin"
theme = "timer-hugo"

# Navbar Menus
[[menu.nav]]
name    = "About"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "Projects"
url     = "projects"
weight  = 3
[[menu.nav]]
name    = "Publications"
url     = "publications"
weight  = 4

# Site Params
[params]
home = "Home"
logo = "images/brain_logo_small.jpeg"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"

# Banner Section
[params.banner]
enable  = true
bgImage = "images/brain.jpg"
heading = "Hi, My name is Jessica and I am"
description = ""
# button
# btn     = true
# btnText = "Download More"
# btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "Doctor in Cognitive Science"
[[params.banner.flipText]]
title   = "Engineer in statistics and scientific computing"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT ME"
content = "I am currently working as an engineer in statistics and scientific computing at the <a href = 'https://lpnc.univ-grenoble-alpes.fr/'>Laboratoire de Psychologie et NeuroCognition</a> and the <a href = 'https://www.lip.univ-smb.fr/'>Laboratoire Inter-universitaire de Psychologie</a> in Chambéry (France).<br><br>Having a PhD in Cognitive Science, my research focuses on studying emotional attention in normal aging and in Alzheimer's Disease, using eye-tracking and neuroimaging tools.<br><br>Please use the following link to find information about my thesis work: link"# Parler de boogui, dev. Rajout éduc et lien thèse cv
image   = "images/profile_small.png"

# Call to Action
[params.cta]
enable  = true
title   = ""
content = ""
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
